// <auto-generated />
using System;
using BugTracker.BugDataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.BugDataContext.Migrations
{
    [DbContext(typeof(BugContext))]
    partial class BugDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.BugDataModel.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ErroneousBehavior")
                        .IsRequired();

                    b.Property<string>("HowToReproduce");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("WorkedTime");

                    b.Property<int>("priorityId");

                    b.Property<int?>("stateId");

                    b.HasKey("Id");

                    b.HasIndex("priorityId");

                    b.HasIndex("stateId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("BugTracker.BugDataModel.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelOfPriority");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("BugTracker.BugDataModel.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("BugTracker.BugDataModel.Bug", b =>
                {
                    b.HasOne("BugTracker.BugDataModel.Priority", "Priority")
                        .WithMany("Bugs")
                        .HasForeignKey("priorityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BugTracker.BugDataModel.State", "state")
                        .WithMany()
                        .HasForeignKey("stateId");
                });
#pragma warning restore 612, 618
        }
    }
}
